### ISSUE TITLE
HTTP API returns non-assigned codepoints

### ISSUE THREAD

**Issue by rhythmus** [mathiasbynens/unicode-data#6]
Despite the value for `property` given `Assigned`, the HTTP API returns non-assigned codepoints.

For example, a query for [Control Pictures](https://mathias.html5.org/data/unicode/format?version=9.0.0&property=Assigned&type=symbols&block=Control-Pictures&prepend=window.symbols%20%3D%20&append=%3B) (Unicode version: 9.0.0, type: symbols, block: Control-Pictures, property: Assigned), returns `\u2400 .. \u243F`, thus including `\u2427 .. \u243F`, which have not been assigned (cfr https://en.wikipedia.org/wiki/Control_Pictures).

**Comment by mathiasbynens** [comment]
This happens because <http://unicode.org/Public/9.0.0/ucd/Blocks.txt> contains this line:

> 2400..243F; Control Pictures

So those characters are in the Control Pictures block, whether they’re assigned or not.

**Comment by mathiasbynens** [comment]
The HTTP API only considers one of these at a time:

 * `category`: can be any Unicode category
 * `script`: can be any Unicode script
 * `property`: can be any Unicode property or derived core property
 * `block`: can be any Unicode block

You can’t combine them into more complicated queries. (Well, you can, but then one of them takes precedence and the other gets ignored.)

**Comment by rhythmus** [comment]
Okay, thanks for clarifying! (And thank you so much for your countless valued contributions to drive forward the state of ubiquitous Unicode support! Ge moet het maar doen… Echt respect en dikke merci!)
